import = [
    "~/.config/alacritty/themes/themes/github_dark_dimmed.toml"
]

[font.normal]
family = "FiraCode Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style  = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style  = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style  = "Italic"

[font]
builtin_box_drawing = false
size = 12

[font.offset]
x = 0
y = 0

[window]
decorations = 'None'
